/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BACKEND.UserManager;
import java.sql.SQLException;
import BACKEND.User;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Kyrab
 */
public class CalanderScreen extends javax.swing.JFrame {
//

    /**
     * Creates new form DairyScreen
     */
    private UserManager b;
    public String dateEntry;

    public CalanderScreen(UserManager inManager) {
        initComponents();

        b = inManager;

        //set Label to ocalDate time
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        dateLbl.setText(dtf.format(now));
        dateLbl1.setText(dtf.format(now));
        dateLbl10.setText(dtf.format(now));
        dateLbl11.setText(dtf.format(now));
        dateLbl2.setText(dtf.format(now));
        dateLbl3.setText(dtf.format(now));
        dateLbl4.setText(dtf.format(now));
        dateLbl5.setText(dtf.format(now));
        dateLbl6.setText(dtf.format(now));
        dateLbl7.setText(dtf.format(now));
        dateLbl8.setText(dtf.format(now));
        dateLbl9.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        dateLbl = new javax.swing.JLabel();
        backBttn = new javax.swing.JButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        janTbl = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane25 = new javax.swing.JScrollPane();
        febTbl = new javax.swing.JTable();
        dateLbl11 = new javax.swing.JLabel();
        backBttn11 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        marchTbl = new javax.swing.JTable();
        dateLbl1 = new javax.swing.JLabel();
        backBttn1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        aprilTbl = new javax.swing.JTable();
        dateLbl2 = new javax.swing.JLabel();
        backBttn2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        mayTbl = new javax.swing.JTable();
        dateLbl3 = new javax.swing.JLabel();
        backBttn3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        juneTbl = new javax.swing.JTable();
        dateLbl4 = new javax.swing.JLabel();
        backBttn4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane26 = new javax.swing.JScrollPane();
        julyTbl = new javax.swing.JTable();
        dateLbl5 = new javax.swing.JLabel();
        backBttn5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        augTbl = new javax.swing.JTable();
        dateLbl6 = new javax.swing.JLabel();
        backBttn6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        septTbl = new javax.swing.JTable();
        dateLbl7 = new javax.swing.JLabel();
        backBttn7 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane22 = new javax.swing.JScrollPane();
        octTbl = new javax.swing.JTable();
        dateLbl8 = new javax.swing.JLabel();
        backBttn8 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane23 = new javax.swing.JScrollPane();
        novTbl = new javax.swing.JTable();
        dateLbl9 = new javax.swing.JLabel();
        backBttn9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane24 = new javax.swing.JScrollPane();
        decTbl = new javax.swing.JTable();
        dateLbl10 = new javax.swing.JLabel();
        backBttn10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setForeground(java.awt.Color.darkGray);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLbl.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl.setText("<date>");
        jPanel2.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn.setText("Back");
        backBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttnActionPerformed(evt);
            }
        });
        jPanel2.add(backBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        janTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", "", "1"},
                {"2", "3", "4", "5", "6", "7", "8"},
                {"9", "10", "11", "12", "13", "14", "15"},
                {"16", "17", "18", "19", "20", "21", "22"},
                {"23", "24", "25", "26", "27", "28", "29"},
                {"30", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        janTbl.setColumnSelectionAllowed(true);
        janTbl.setRowHeight(50);
        janTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        janTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        janTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                janTblMouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(janTbl);
        janTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel2.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        jTabbedPane1.addTab("Jan", jPanel2);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        febTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "1", "2", "3", "4", "5"},
                {"6", "7", "8", "9", "10", "11", "12"},
                {"13", "14", "15", "16", "17", "18", "19"},
                {"20", "21", "22", "23", "24", "25", "26"},
                {"27", "28", "", "", "", "", ""},
                {"30", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        febTbl.setColumnSelectionAllowed(true);
        febTbl.setRowHeight(50);
        febTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        febTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                febTblMouseClicked(evt);
            }
        });
        jScrollPane25.setViewportView(febTbl);
        febTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel4.add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 450, 270));

        dateLbl11.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl11.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl11.setText("<date>");
        jPanel4.add(dateLbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn11.setText("Back");
        backBttn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn11ActionPerformed(evt);
            }
        });
        jPanel4.add(backBttn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("Feb", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marchTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "1", "2", "3", "4", "5"},
                {"6", "7", "8", "9", "10", "11", "12"},
                {"13", "14", "15", "16", "17", "18", "19"},
                {"20", "21", "22", "23", "24", "25", "26"},
                {"27", "28", "", "", "", "", ""},
                {"", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        marchTbl.setColumnSelectionAllowed(true);
        marchTbl.setRowHeight(50);
        marchTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        marchTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marchTblMouseClicked(evt);
            }
        });
        jScrollPane16.setViewportView(marchTbl);
        marchTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel5.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        dateLbl1.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl1.setText("<date>");
        jPanel5.add(dateLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn1.setText("Back");
        backBttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn1ActionPerformed(evt);
            }
        });
        jPanel5.add(backBttn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("March", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aprilTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", "1", "2"},
                {"3", "4", "5", "6", "7", "8", "9"},
                {"10", "11", "12", "13", "14", "15", "16"},
                {"17", "18", "19", "20", "21", "22", "23"},
                {"24", "25", "26", "27", "28", "29", "30"},
                {"30", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        aprilTbl.setColumnSelectionAllowed(true);
        aprilTbl.setRowHeight(50);
        aprilTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        aprilTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aprilTblMouseClicked(evt);
            }
        });
        jScrollPane17.setViewportView(aprilTbl);
        aprilTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel6.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        dateLbl2.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl2.setText("<date>");
        jPanel6.add(dateLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn2.setText("Back");
        backBttn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn2ActionPerformed(evt);
            }
        });
        jPanel6.add(backBttn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("April", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 204, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mayTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2", "3", "4", "5", "6", "7"},
                {"8", "9", "10", "11", "12", "13", "14"},
                {"15", "16", "17", "18", "19", "20", "21"},
                {"22", "23", "24", "25", "26", "27", "28"},
                {"29", "30", "29", "", "", "", ""},
                {"", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        mayTbl.setColumnSelectionAllowed(true);
        mayTbl.setRowHeight(50);
        mayTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mayTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mayTblMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(mayTbl);
        mayTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel7.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        dateLbl3.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl3.setText("<date>");
        jPanel7.add(dateLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn3.setText("Back");
        backBttn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn3ActionPerformed(evt);
            }
        });
        jPanel7.add(backBttn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("May", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        juneTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "1", "2", "3", "4"},
                {"5", "6", "7", "8", "9", "10", "11"},
                {"12", "13", "14", "15", "16", "17", "18"},
                {"19", "20", "21", "22", "23", "24", "25"},
                {"26", "27", "28", "29", "30", "", ""},
                {"30", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        juneTbl.setColumnSelectionAllowed(true);
        juneTbl.setRowHeight(50);
        juneTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        juneTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juneTblMouseClicked(evt);
            }
        });
        jScrollPane19.setViewportView(juneTbl);
        juneTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel8.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        dateLbl4.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl4.setText("<date>");
        jPanel8.add(dateLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn4.setText("Back");
        backBttn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn4ActionPerformed(evt);
            }
        });
        jPanel8.add(backBttn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("June", jPanel8);

        jPanel9.setBackground(new java.awt.Color(204, 255, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        julyTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", "1", "2"},
                {"3", "4", "5", "6", "7", "8", "9"},
                {"10", "11", "12", "13", "14", "15", "16"},
                {"17", "18", "19", "20", "21", "22", "23"},
                {"24", "25", "26", "27", "28", "29", "30"},
                {"30", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        julyTbl.setColumnSelectionAllowed(true);
        julyTbl.setRowHeight(50);
        julyTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        julyTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                julyTblMouseClicked(evt);
            }
        });
        jScrollPane26.setViewportView(julyTbl);
        julyTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel9.add(jScrollPane26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        dateLbl5.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl5.setText("<date>");
        jPanel9.add(dateLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn5.setText("Back");
        backBttn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn5ActionPerformed(evt);
            }
        });
        jPanel9.add(backBttn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("July", jPanel9);

        jPanel10.setBackground(new java.awt.Color(153, 255, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        augTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "1", "2", "3", "4", "5", "6"},
                {"7", "8", "9", "10", "11", "12", "13"},
                {"14", "15", "16", "17", "18", "19", "20"},
                {"21", "22", "23", "24", "25", "26", "27"},
                {"28", "29", "30", "31", "", "", ""},
                {"30", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        augTbl.setColumnSelectionAllowed(true);
        augTbl.setRowHeight(50);
        augTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        augTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                augTblMouseClicked(evt);
            }
        });
        jScrollPane20.setViewportView(augTbl);
        augTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel10.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        dateLbl6.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl6.setText("<date>");
        jPanel10.add(dateLbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn6.setText("Back");
        backBttn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn6ActionPerformed(evt);
            }
        });
        jPanel10.add(backBttn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("Aug", jPanel10);

        jPanel11.setBackground(new java.awt.Color(153, 255, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        septTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "1", "2", "3"},
                {"4", "5", "6", "7", "8", "9", "10"},
                {"11", "12", "13", "14", "15", "16", "17"},
                {"18", "19", "20", "21", "22", "23", "24"},
                {"25", "26", "27", "28", "29", "30", ""},
                {"30", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        septTbl.setColumnSelectionAllowed(true);
        septTbl.setRowHeight(50);
        septTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        septTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                septTblMouseClicked(evt);
            }
        });
        jScrollPane21.setViewportView(septTbl);
        septTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel11.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        dateLbl7.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl7.setText("<date>");
        jPanel11.add(dateLbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn7.setText("Back");
        backBttn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn7ActionPerformed(evt);
            }
        });
        jPanel11.add(backBttn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("Sept", jPanel11);

        jPanel12.setBackground(new java.awt.Color(153, 255, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        octTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", "", "1"},
                {"2", "3", "4", "5", "6", "7", "8"},
                {"9", "10", "11", "12", "13", "14", "15"},
                {"16", "17", "18", "19", "20", "21", "22"},
                {"23", "24", "25", "26", "27", "28", "29"},
                {"30", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        octTbl.setRowHeight(50);
        octTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        octTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                octTblMouseClicked(evt);
            }
        });
        jScrollPane22.setViewportView(octTbl);
        octTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel12.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        dateLbl8.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl8.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl8.setText("<date>");
        jPanel12.add(dateLbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn8.setText("Back");
        backBttn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn8ActionPerformed(evt);
            }
        });
        jPanel12.add(backBttn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("Oct", jPanel12);

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        novTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "1", "2", "3", "4", "5"},
                {"6", "7", "8", "9", "10", "11", "12"},
                {"13", "14", "15", "16", "17", "18", "19"},
                {"20", "21", "22", "23", "24", "25", "26"},
                {"27", "28", "29", "30", "", "", ""},
                {"30", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        novTbl.setColumnSelectionAllowed(true);
        novTbl.setRowHeight(50);
        novTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        novTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novTblMouseClicked(evt);
            }
        });
        jScrollPane23.setViewportView(novTbl);
        novTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel13.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        dateLbl9.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl9.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl9.setText("<date>");
        jPanel13.add(dateLbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn9.setText("Back");
        backBttn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn9ActionPerformed(evt);
            }
        });
        jPanel13.add(backBttn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("Nov", jPanel13);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "1", "2", "3"},
                {"4", "5", "6", "7", "8", "9", "10"},
                {"11", "12", "13", "14", "15", "16", "17"},
                {"18", "19", "20", "21", "22", "23", "24"},
                {"25", "26", "27", "28", "29", "30", "31"},
                {"30", null, null, null, null, null, null}
            },
            new String [] {
                "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
            }
        ));
        decTbl.setColumnSelectionAllowed(true);
        decTbl.setRowHeight(50);
        decTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        decTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decTblMouseClicked(evt);
            }
        });
        jScrollPane24.setViewportView(decTbl);
        decTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel3.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 270));

        dateLbl10.setBackground(new java.awt.Color(0, 102, 204));
        dateLbl10.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        dateLbl10.setText("<date>");
        jPanel3.add(dateLbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        backBttn10.setText("Back");
        backBttn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn10ActionPerformed(evt);
            }
        });
        jPanel3.add(backBttn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jTabbedPane1.addTab("Dec", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttnActionPerformed
        // TODO add your handling code here:
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttnActionPerformed


    private void janTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_janTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("January"))) {
            janTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            janTbl.setEnabled(false);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }


    }//GEN-LAST:event_janTblMouseClicked

    private void marchTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marchTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("march"))) {
            marchTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            marchTbl.setEnabled(false);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_marchTblMouseClicked

    private void aprilTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aprilTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("april"))) {
            aprilTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            aprilTbl.setEnabled(false);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_aprilTblMouseClicked

    private void mayTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mayTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("may"))) {
            mayTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            mayTbl.setEnabled(false);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_mayTblMouseClicked

    private void juneTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juneTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("june"))) {
            juneTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            juneTbl.setEnabled(false);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_juneTblMouseClicked

    private void augTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_augTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("august"))) {
            augTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            augTbl.setEnabled(false);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_augTblMouseClicked

    private void septTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_septTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("september"))) {
            septTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            septTbl.setEnabled(true);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_septTblMouseClicked

    private void octTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_octTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("october"))) {
            octTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            octTbl.setEnabled(true);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_octTblMouseClicked

    private void novTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("November"))) {
            novTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            novTbl.setEnabled(true);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_novTblMouseClicked

    private void decTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("december"))) {
            decTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            decTbl.setEnabled(true);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_decTblMouseClicked

    private void febTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_febTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("Feburary"))) {
            febTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            febTbl.setEnabled(true);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_febTblMouseClicked

    private void julyTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_julyTblMouseClicked
        LocalDate now = LocalDate.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMMM");
        String currentD = dtf.format(now);
        if (!(currentD.equalsIgnoreCase("july"))) {
            julyTbl.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Make sure your entry is on the current date");
        } else {
            julyTbl.setEnabled(true);
            dispose();
            new DiaryEntry(b).setVisible(true);
        }
    }//GEN-LAST:event_julyTblMouseClicked

    private void backBttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn1ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn1ActionPerformed

    private void backBttn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn2ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn2ActionPerformed

    private void backBttn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn3ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn3ActionPerformed

    private void backBttn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn4ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn4ActionPerformed

    private void backBttn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn5ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn5ActionPerformed

    private void backBttn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn6ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn6ActionPerformed

    private void backBttn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn7ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn7ActionPerformed

    private void backBttn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn8ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn8ActionPerformed

    private void backBttn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn9ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn9ActionPerformed

    private void backBttn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn10ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn10ActionPerformed

    private void backBttn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn11ActionPerformed
        dispose();
        new HomeScreen(b).setVisible(true);

    }//GEN-LAST:event_backBttn11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable aprilTbl;
    private javax.swing.JTable augTbl;
    private javax.swing.JButton backBttn;
    private javax.swing.JButton backBttn1;
    private javax.swing.JButton backBttn10;
    private javax.swing.JButton backBttn11;
    private javax.swing.JButton backBttn2;
    private javax.swing.JButton backBttn3;
    private javax.swing.JButton backBttn4;
    private javax.swing.JButton backBttn5;
    private javax.swing.JButton backBttn6;
    private javax.swing.JButton backBttn7;
    private javax.swing.JButton backBttn8;
    private javax.swing.JButton backBttn9;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel dateLbl1;
    private javax.swing.JLabel dateLbl10;
    private javax.swing.JLabel dateLbl11;
    private javax.swing.JLabel dateLbl2;
    private javax.swing.JLabel dateLbl3;
    private javax.swing.JLabel dateLbl4;
    private javax.swing.JLabel dateLbl5;
    private javax.swing.JLabel dateLbl6;
    private javax.swing.JLabel dateLbl7;
    private javax.swing.JLabel dateLbl8;
    private javax.swing.JLabel dateLbl9;
    private javax.swing.JTable decTbl;
    private javax.swing.JTable febTbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable janTbl;
    private javax.swing.JTable julyTbl;
    private javax.swing.JTable juneTbl;
    private javax.swing.JTable marchTbl;
    private javax.swing.JTable mayTbl;
    private javax.swing.JTable novTbl;
    private javax.swing.JTable octTbl;
    private javax.swing.JTable septTbl;
    // End of variables declaration//GEN-END:variables
}
