/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author Kyrab
 */
import BACKEND.UserManager;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class DiaryEntry extends javax.swing.JFrame {

    /**
     * Creates new form DiaryEntry
     */
    private UserManager v;

    public DiaryEntry(UserManager inManager) {
        initComponents();

        v = inManager;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        entryTxtArea = new javax.swing.JTextArea();
        headingTxtField = new javax.swing.JTextField();
        submitBttn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBttn.setText("Back");
        backBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttnActionPerformed(evt);
            }
        });
        jPanel1.add(backBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        entryTxtArea.setColumns(20);
        entryTxtArea.setRows(5);
        jScrollPane1.setViewportView(entryTxtArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 370, 270));

        headingTxtField.setText("<Heading>");
        jPanel1.add(headingTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 190, 30));

        submitBttn.setText("Submit");
        submitBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBttnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cave.png"))); // NOI18N
        jLabel1.setLabelFor(this);
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 504, 463));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttnActionPerformed
        // TODO add your handling code here:
        String diaryHeading = headingTxtField.getText();
        String diaryContent = entryTxtArea.getText();
        int currentUserId = v.getCurrentUser();
        LocalDate date = LocalDate.now();
        
        try {
            v.addDiaryEntry(currentUserId,date, diaryContent, diaryHeading);
            JFrame l = new JFrame();
            JOptionPane.showMessageDialog(l, "added to library");
        } catch (SQLException ex) {
            JFrame k = new JFrame();
            JOptionPane.showMessageDialog(k, "could not load successfully");

            Logger.getLogger(DiaryEntry.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_submitBttnActionPerformed

    private void backBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttnActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new HomeScreen(v).setVisible(true);

    }//GEN-LAST:event_backBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBttn;
    private javax.swing.JTextArea entryTxtArea;
    private javax.swing.JTextField headingTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitBttn;
    // End of variables declaration//GEN-END:variables
}
