/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import BACKEND.User;
import BACKEND.UserManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kyrab
 */
public class EntryScreen extends javax.swing.JFrame {

    /**
     * Creates new form EntryScreen
     */
    private UserManager n ;
    public String currentUser;
    
    public EntryScreen(UserManager inManager) {
        initComponents();
        
        n = inManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        SignUpBttn = new javax.swing.JButton();
        LogInBttn = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();
        cloudLbl3 = new javax.swing.JLabel();
        cloudLbl1 = new javax.swing.JLabel();
        cloudLbl2 = new javax.swing.JLabel();
        cloudLbl = new javax.swing.JLabel();
        userProfileLbl = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 180, 30));
        jPanel2.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 180, 30));

        SignUpBttn.setText("Sign Up");
        SignUpBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBttnActionPerformed(evt);
            }
        });
        jPanel2.add(SignUpBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 150, 30));

        LogInBttn.setText("Log In");
        LogInBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBttnActionPerformed(evt);
            }
        });
        jPanel2.add(LogInBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 150, 30));

        label2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 11)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 153, 204));
        label2.setText("PASSWORD:");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 80, -1));
        jPanel2.add(cloudLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, 210));

        cloudLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clouds.png"))); // NOI18N
        jPanel2.add(cloudLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 270, 230));

        cloudLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clouds.png"))); // NOI18N
        jPanel2.add(cloudLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 220, 260, 180));

        cloudLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clouds.png"))); // NOI18N
        jPanel2.add(cloudLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 260, 180));

        userProfileLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user (2).png"))); // NOI18N
        jPanel2.add(userProfileLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 170, 150));

        label1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 11)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 153, 204));
        label1.setText("USERNAME:");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 560, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBttnActionPerformed
        // TODO add your handling code here:
        String username = usernameField.getText();
        String pass = passwordField.getText();
        if (n.checkUser(username, pass)) {
            
            
            dispose();
            new HomeScreen(n).setVisible(true);

        } else {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Incorrect username or password");
        }

    }//GEN-LAST:event_LogInBttnActionPerformed

    private void SignUpBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBttnActionPerformed
        // TODO add your handling code here:
        dispose();
        new SignUpScreen(n).setVisible(true);
    }//GEN-LAST:event_SignUpBttnActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInBttn;
    private javax.swing.JButton SignUpBttn;
    private javax.swing.JLabel cloudLbl;
    private javax.swing.JLabel cloudLbl1;
    private javax.swing.JLabel cloudLbl2;
    private javax.swing.JLabel cloudLbl3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel userProfileLbl;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
