/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BACKEND.UserManager;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kyra Balliram
 */
public class FeelingsScreen extends javax.swing.JFrame {

    /**
     * Creates new form FeelingsScreen
     */
    private UserManager m;

    public FeelingsScreen(UserManager inManager) {
        initComponents();
        m = inManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMain = new javax.swing.JPanel();
        jp1 = new javax.swing.JPanel();
        happyScale = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activityTxtarea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        submitBttn3 = new javax.swing.JButton();
        sleepScale = new javax.swing.JSlider();
        jLabel22 = new javax.swing.JLabel();
        exerciseHabits = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        eatingHabits = new javax.swing.JComboBox<>();
        jp4 = new javax.swing.JPanel();
        happyScale3 = new javax.swing.JSlider();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        activityTxtarea3 = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        submitBttn6 = new javax.swing.JButton();
        sleepScale3 = new javax.swing.JSlider();
        jLabel36 = new javax.swing.JLabel();
        exerciseHabits3 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        eatingHabits3 = new javax.swing.JComboBox<>();
        jp3 = new javax.swing.JPanel();
        happyScale2 = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        activityTxtarea2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        submitBttn4 = new javax.swing.JButton();
        sleepScale2 = new javax.swing.JSlider();
        jLabel32 = new javax.swing.JLabel();
        exerciseHabits2 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        eatingHabits2 = new javax.swing.JComboBox<>();
        jp5 = new javax.swing.JPanel();
        happyScale4 = new javax.swing.JSlider();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        activityTxtarea4 = new javax.swing.JTextArea();
        jLabel41 = new javax.swing.JLabel();
        submitBttn7 = new javax.swing.JButton();
        sleepScale4 = new javax.swing.JSlider();
        jLabel42 = new javax.swing.JLabel();
        exerciseHabits4 = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        eatingHabits4 = new javax.swing.JComboBox<>();
        jp2 = new javax.swing.JPanel();
        happyScale1 = new javax.swing.JSlider();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        activityTxtarea1 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        submitBttn5 = new javax.swing.JButton();
        sleepScale1 = new javax.swing.JSlider();
        jLabel29 = new javax.swing.JLabel();
        exerciseHabits1 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        eatingHabits1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        happyLbl = new javax.swing.JLabel();
        happyTxt = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        goodLbl = new javax.swing.JLabel();
        goodTxt = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        normalLbl = new javax.swing.JLabel();
        normalTxt = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        sadLbl = new javax.swing.JLabel();
        sadTxt = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        unhappyLbl = new javax.swing.JLabel();
        unhappyTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMain.setBackground(new java.awt.Color(204, 204, 204));

        jp1.setBackground(new java.awt.Color(204, 204, 255));
        jp1.setPreferredSize(new java.awt.Dimension(567, 425));
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        happyScale.setForeground(new java.awt.Color(102, 102, 255));
        happyScale.setMajorTickSpacing(1);
        happyScale.setMaximum(10);
        happyScale.setMinimum(1);
        happyScale.setMinorTickSpacing(1);
        happyScale.setPaintLabels(true);
        jp1.add(happyScale, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 210, -1));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Happy");
        jp1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 60, -1));

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Uhnappy");
        jp1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("What have you been up too?");
        jp1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, 40));

        jScrollPane1.setForeground(new java.awt.Color(102, 102, 255));

        activityTxtarea.setColumns(20);
        activityTxtarea.setRows(5);
        jScrollPane1.setViewportView(activityTxtarea);

        jp1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 310, 90));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Have you exercised today?");
        jp1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 240, -1));

        submitBttn3.setForeground(new java.awt.Color(102, 102, 255));
        submitBttn3.setText("Submit");
        submitBttn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBttn3ActionPerformed(evt);
            }
        });
        jp1.add(submitBttn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        sleepScale.setForeground(new java.awt.Color(102, 102, 255));
        sleepScale.setMajorTickSpacing(5);
        sleepScale.setMaximum(24);
        sleepScale.setMinorTickSpacing(5);
        sleepScale.setPaintLabels(true);
        jp1.add(sleepScale, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 270, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 255));
        jLabel22.setText("Have you been eating regurlarly?");
        jp1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 240, 30));

        exerciseHabits.setForeground(new java.awt.Color(102, 102, 255));
        exerciseHabits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " ", " " }));
        jp1.add(exerciseHabits, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 200, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 255));
        jLabel23.setText("How many hours did you sleep last night?");
        jp1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 310, -1));

        eatingHabits.setForeground(new java.awt.Color(102, 102, 255));
        eatingHabits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " ", " " }));
        jp1.add(eatingHabits, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 200, -1));

        jp4.setBackground(new java.awt.Color(204, 255, 204));
        jp4.setPreferredSize(new java.awt.Dimension(567, 425));
        jp4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        happyScale3.setForeground(new java.awt.Color(0, 153, 102));
        happyScale3.setMajorTickSpacing(1);
        happyScale3.setMaximum(10);
        happyScale3.setMinimum(1);
        happyScale3.setMinorTickSpacing(1);
        happyScale3.setPaintLabels(true);
        jp4.add(happyScale3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 210, -1));

        jLabel28.setBackground(new java.awt.Color(153, 153, 255));
        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 102));
        jLabel28.setText("Happy");
        jp4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 60, -1));

        jLabel31.setBackground(new java.awt.Color(153, 153, 255));
        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 102));
        jLabel31.setText("Uhnappy");
        jp4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, -1));

        jLabel34.setBackground(new java.awt.Color(153, 153, 255));
        jLabel34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 153, 102));
        jLabel34.setText("What have you been up too?");
        jp4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, 40));

        jScrollPane7.setForeground(new java.awt.Color(0, 153, 102));

        activityTxtarea3.setColumns(20);
        activityTxtarea3.setRows(5);
        jScrollPane7.setViewportView(activityTxtarea3);

        jp4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 310, 90));

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 153, 102));
        jLabel35.setText("Have you exercised today?");
        jp4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 240, -1));

        submitBttn6.setForeground(new java.awt.Color(0, 153, 102));
        submitBttn6.setText("Submit");
        submitBttn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBttn6ActionPerformed(evt);
            }
        });
        jp4.add(submitBttn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        sleepScale3.setForeground(new java.awt.Color(0, 153, 102));
        sleepScale3.setMajorTickSpacing(5);
        sleepScale3.setMaximum(24);
        sleepScale3.setMinorTickSpacing(5);
        sleepScale3.setPaintLabels(true);
        jp4.add(sleepScale3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 270, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 153, 102));
        jLabel36.setText("Have you been eating regurlarly?");
        jp4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 240, 30));

        exerciseHabits3.setForeground(new java.awt.Color(0, 153, 102));
        exerciseHabits3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " ", " " }));
        jp4.add(exerciseHabits3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 200, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 153, 102));
        jLabel37.setText("How many hours did you sleep last night?");
        jp4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 310, -1));

        eatingHabits3.setForeground(new java.awt.Color(0, 153, 102));
        eatingHabits3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " ", " " }));
        jp4.add(eatingHabits3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 200, -1));

        jp3.setBackground(new java.awt.Color(255, 255, 204));
        jp3.setPreferredSize(new java.awt.Dimension(567, 425));
        jp3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        happyScale2.setMajorTickSpacing(1);
        happyScale2.setMaximum(10);
        happyScale2.setMinimum(1);
        happyScale2.setMinorTickSpacing(1);
        happyScale2.setPaintLabels(true);
        jp3.add(happyScale2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 210, -1));

        jLabel9.setBackground(new java.awt.Color(153, 153, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 0));
        jLabel9.setText("Happy");
        jp3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 60, -1));

        jLabel10.setBackground(new java.awt.Color(153, 153, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 0));
        jLabel10.setText("Uhnappy");
        jp3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, -1));

        jLabel11.setBackground(new java.awt.Color(153, 153, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 0));
        jLabel11.setText("What have you been up too?");
        jp3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, 40));

        activityTxtarea2.setColumns(20);
        activityTxtarea2.setRows(5);
        jScrollPane3.setViewportView(activityTxtarea2);

        jp3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 310, 90));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 0));
        jLabel12.setText("Have you exercised today?");
        jp3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 240, -1));

        submitBttn4.setText("Submit");
        submitBttn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBttn4ActionPerformed(evt);
            }
        });
        jp3.add(submitBttn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        sleepScale2.setMajorTickSpacing(5);
        sleepScale2.setMaximum(24);
        sleepScale2.setMinorTickSpacing(5);
        sleepScale2.setPaintLabels(true);
        jp3.add(sleepScale2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 270, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 153, 0));
        jLabel32.setText("Have you been eating regurlarly?");
        jp3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 240, 30));

        exerciseHabits2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " ", " " }));
        jp3.add(exerciseHabits2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 200, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 153, 0));
        jLabel33.setText("How many hours did you sleep last night?");
        jp3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 310, -1));

        eatingHabits2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " ", " " }));
        jp3.add(eatingHabits2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 200, -1));

        jp5.setBackground(new java.awt.Color(255, 153, 153));
        jp5.setPreferredSize(new java.awt.Dimension(567, 425));
        jp5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        happyScale4.setForeground(new java.awt.Color(204, 51, 0));
        happyScale4.setMajorTickSpacing(1);
        happyScale4.setMaximum(10);
        happyScale4.setMinimum(1);
        happyScale4.setMinorTickSpacing(1);
        happyScale4.setPaintLabels(true);
        jp5.add(happyScale4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 210, -1));

        jLabel38.setBackground(new java.awt.Color(153, 153, 255));
        jLabel38.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 51, 0));
        jLabel38.setText("Happy");
        jp5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 60, -1));

        jLabel39.setBackground(new java.awt.Color(153, 153, 255));
        jLabel39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 51, 0));
        jLabel39.setText("Uhnappy");
        jp5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, -1));

        jLabel40.setBackground(new java.awt.Color(153, 153, 255));
        jLabel40.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 51, 0));
        jLabel40.setText("What have you been up too?");
        jp5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, 40));

        jScrollPane8.setForeground(new java.awt.Color(204, 51, 0));

        activityTxtarea4.setColumns(20);
        activityTxtarea4.setRows(5);
        jScrollPane8.setViewportView(activityTxtarea4);

        jp5.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 310, 90));

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 51, 0));
        jLabel41.setText("Have you exercised today?");
        jp5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 240, -1));

        submitBttn7.setForeground(new java.awt.Color(204, 51, 0));
        submitBttn7.setText("Submit");
        submitBttn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBttn7ActionPerformed(evt);
            }
        });
        jp5.add(submitBttn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        sleepScale4.setForeground(new java.awt.Color(204, 51, 0));
        sleepScale4.setMajorTickSpacing(5);
        sleepScale4.setMaximum(24);
        sleepScale4.setMinorTickSpacing(5);
        sleepScale4.setPaintLabels(true);
        jp5.add(sleepScale4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 270, -1));

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 51, 0));
        jLabel42.setText("Have you been eating regurlarly?");
        jp5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 240, 30));

        exerciseHabits4.setForeground(new java.awt.Color(204, 51, 0));
        exerciseHabits4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " ", " " }));
        jp5.add(exerciseHabits4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 200, -1));

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 51, 0));
        jLabel43.setText("How many hours did you sleep last night?");
        jp5.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 310, -1));

        eatingHabits4.setForeground(new java.awt.Color(204, 51, 0));
        eatingHabits4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " ", " " }));
        jp5.add(eatingHabits4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 200, -1));

        jp2.setBackground(new java.awt.Color(255, 204, 255));
        jp2.setPreferredSize(new java.awt.Dimension(567, 425));
        jp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        happyScale1.setForeground(new java.awt.Color(255, 102, 255));
        happyScale1.setMajorTickSpacing(1);
        happyScale1.setMaximum(10);
        happyScale1.setMinimum(1);
        happyScale1.setMinorTickSpacing(1);
        happyScale1.setPaintLabels(true);
        jp2.add(happyScale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 210, -1));

        jLabel24.setBackground(new java.awt.Color(153, 153, 255));
        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 102, 255));
        jLabel24.setText("Happy");
        jp2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 60, -1));

        jLabel25.setBackground(new java.awt.Color(255, 102, 255));
        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 102, 255));
        jLabel25.setText("Uhnappy");
        jp2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, -1));

        jLabel26.setBackground(new java.awt.Color(153, 153, 255));
        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 102, 255));
        jLabel26.setText("What have you been up too?");
        jp2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, 40));

        jScrollPane6.setForeground(new java.awt.Color(255, 102, 255));

        activityTxtarea1.setColumns(20);
        activityTxtarea1.setRows(5);
        jScrollPane6.setViewportView(activityTxtarea1);

        jp2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 310, 90));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 102, 255));
        jLabel27.setText("Have you exercised today?");
        jp2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 240, -1));

        submitBttn5.setForeground(new java.awt.Color(255, 102, 255));
        submitBttn5.setText("Submit");
        submitBttn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBttn5ActionPerformed(evt);
            }
        });
        jp2.add(submitBttn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        sleepScale1.setForeground(new java.awt.Color(255, 102, 255));
        sleepScale1.setMajorTickSpacing(5);
        sleepScale1.setMaximum(24);
        sleepScale1.setMinorTickSpacing(5);
        sleepScale1.setPaintLabels(true);
        jp2.add(sleepScale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 270, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 102, 255));
        jLabel29.setText("Have you been eating regurlarly?");
        jp2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 240, 30));

        exerciseHabits1.setForeground(new java.awt.Color(255, 102, 255));
        exerciseHabits1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " ", " " }));
        jp2.add(exerciseHabits1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 200, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 102, 255));
        jLabel30.setText("How many hours did you sleep last night?");
        jp2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 310, -1));

        eatingHabits1.setForeground(new java.awt.Color(255, 102, 255));
        eatingHabits1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " ", " " }));
        jp2.add(eatingHabits1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 200, -1));

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpMainLayout.createSequentialGroup()
                    .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpMainLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpMainLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jpMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 0, 410, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab1.setBackground(new java.awt.Color(204, 204, 255));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        happyLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/happyIcon.png"))); // NOI18N

        happyTxt.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        happyTxt.setForeground(new java.awt.Color(153, 153, 255));
        happyTxt.setText("HAPPY");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addComponent(happyLbl)
                .addGap(18, 18, 18)
                .addComponent(happyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addComponent(happyLbl)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(happyTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, -1, 60));

        tab2.setBackground(new java.awt.Color(255, 204, 255));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        goodLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goodIcon.png"))); // NOI18N

        goodTxt.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        goodTxt.setForeground(new java.awt.Color(255, 102, 255));
        goodTxt.setText("GOOD");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addComponent(goodLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goodTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addComponent(goodLbl)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(goodTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        tab3.setBackground(new java.awt.Color(255, 255, 204));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        normalLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/normalIcon.png"))); // NOI18N

        normalTxt.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        normalTxt.setForeground(new java.awt.Color(255, 204, 102));
        normalTxt.setText("NORMAL");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addComponent(normalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(normalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addComponent(normalLbl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(normalTxt)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        tab4.setBackground(new java.awt.Color(204, 255, 204));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        sadLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sadIcon.png"))); // NOI18N

        sadTxt.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        sadTxt.setForeground(new java.awt.Color(51, 153, 0));
        sadTxt.setText("SAD");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addComponent(sadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addComponent(sadLbl)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(sadTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(tab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        tab5.setBackground(new java.awt.Color(255, 153, 153));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        unhappyLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unhappyIcon.png"))); // NOI18N

        unhappyTxt.setBackground(new java.awt.Color(0, 102, 102));
        unhappyTxt.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        unhappyTxt.setForeground(new java.awt.Color(255, 51, 102));
        unhappyTxt.setText("UNHAPPY");

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addComponent(unhappyLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unhappyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addComponent(unhappyLbl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(tab5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(unhappyTxt)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(tab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        // TODO add your handling code here:

        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);


    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        // TODO add your handling code here:
        jp1.setVisible(false);
        jp2.setVisible(true);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        // TODO add your handling code here:
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(true);
        jp4.setVisible(false);
        jp5.setVisible(false);
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        // TODO add your handling code here:
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(true);
        jp5.setVisible(false);
    }//GEN-LAST:event_tab4MouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        // TODO add your handling code here:
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(true);
    }//GEN-LAST:event_tab5MouseClicked

    private void submitBttn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttn3ActionPerformed
        int userId = m.getCurrentUser();
        String activitiesStr = activityTxtarea.getText();
        LocalDateTime now = LocalDateTime.now();
        int moodScore = happyScale.getValue();
        int sleepScore = sleepScale.getValue();
        String eatingScoreStr = eatingHabits.getSelectedItem().toString();
        String exerciseScoreStr = exerciseHabits.getSelectedItem().toString();
        int eatingScore = 0;
        int exScore = 0;

        if (eatingScoreStr.equalsIgnoreCase("Yes")) {
            eatingScore = 1;
        }

        if (exerciseScoreStr.equalsIgnoreCase("Yes")) {
            exScore = 1;
        }

        try {
            m.addMood(userId, now, sleepScore, moodScore, exScore, eatingScore, activitiesStr);
            dispose();
            new HomeScreen(m).setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FeelingsScreen.class.getName()).log(Level.SEVERE, null, ex);
            JFrame x = new JFrame();
            JOptionPane.showMessageDialog(x, "There was an error");
        }


    }//GEN-LAST:event_submitBttn3ActionPerformed

    private void submitBttn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttn5ActionPerformed
        int userId = m.getCurrentUser();
        String activitiesStr = activityTxtarea.getText();
        LocalDateTime now = LocalDateTime.now();
        int moodScore = happyScale.getValue();
        int sleepScore = sleepScale.getValue();
        String eatingScoreStr = eatingHabits.getSelectedItem().toString();
        String exerciseScoreStr = exerciseHabits.getSelectedItem().toString();
        int eatingScore = 0;
        int exScore = 0;

        if (eatingScoreStr.equalsIgnoreCase("Yes")) {
            eatingScore = 1;
        }

        if (exerciseScoreStr.equalsIgnoreCase("Yes")) {
            exScore = 1;
        }

        try {
            m.addMood(userId, now, sleepScore, moodScore, exScore, eatingScore, activitiesStr);
            dispose();
            new HomeScreen(m).setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FeelingsScreen.class.getName()).log(Level.SEVERE, null, ex);
            JFrame x = new JFrame();
            JOptionPane.showMessageDialog(x, "There was an error");
        }


    }//GEN-LAST:event_submitBttn5ActionPerformed

    private void submitBttn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttn4ActionPerformed
        int userId = m.getCurrentUser();
        String activitiesStr = activityTxtarea.getText();
        LocalDateTime now = LocalDateTime.now();
        int moodScore = happyScale.getValue();
        int sleepScore = sleepScale.getValue();
        String eatingScoreStr = eatingHabits.getSelectedItem().toString();
        String exerciseScoreStr = exerciseHabits.getSelectedItem().toString();
        int eatingScore = 0;
        int exScore = 0;

        if (eatingScoreStr.equalsIgnoreCase("Yes")) {
            eatingScore = 1;
        }

        if (exerciseScoreStr.equalsIgnoreCase("Yes")) {
            exScore = 1;
        }

        try {
            m.addMood(userId, now, sleepScore, moodScore, exScore, eatingScore, activitiesStr);
            dispose();
            new HomeScreen(m).setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FeelingsScreen.class.getName()).log(Level.SEVERE, null, ex);
            JFrame x = new JFrame();
            JOptionPane.showMessageDialog(x, "There was an error");
        }


    }//GEN-LAST:event_submitBttn4ActionPerformed

    private void submitBttn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttn6ActionPerformed
        int userId = m.getCurrentUser();
        String activitiesStr = activityTxtarea.getText();
        LocalDateTime now = LocalDateTime.now();
        int moodScore = happyScale.getValue();
        int sleepScore = sleepScale.getValue();
        String eatingScoreStr = eatingHabits.getSelectedItem().toString();
        String exerciseScoreStr = exerciseHabits.getSelectedItem().toString();
        int eatingScore = 0;
        int exScore = 0;

        if (eatingScoreStr.equalsIgnoreCase("Yes")) {
            eatingScore = 1;
        }

        if (exerciseScoreStr.equalsIgnoreCase("Yes")) {
            exScore = 1;
        }

        try {
            m.addMood(userId, now, sleepScore, moodScore, exScore, eatingScore, activitiesStr);
            dispose();
            new HomeScreen(m).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FeelingsScreen.class.getName()).log(Level.SEVERE, null, ex);
            JFrame x = new JFrame();
            JOptionPane.showMessageDialog(x, "There was an error");
        }


    }//GEN-LAST:event_submitBttn6ActionPerformed

    private void submitBttn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBttn7ActionPerformed
        int userId = m.getCurrentUser();
        String activitiesStr = activityTxtarea.getText();
        LocalDateTime now = LocalDateTime.now();
        int moodScore = happyScale.getValue();
        int sleepScore = sleepScale.getValue();
        String eatingScoreStr = eatingHabits.getSelectedItem().toString();
        String exerciseScoreStr = exerciseHabits.getSelectedItem().toString();
        int eatingScore = 0;
        int exScore = 0;

        if (eatingScoreStr.equalsIgnoreCase("Yes")) {
            eatingScore = 1;
        }

        if (exerciseScoreStr.equalsIgnoreCase("Yes")) {
            exScore = 1;
        }

        try {
            m.addMood(userId, now, sleepScore, moodScore, exScore, eatingScore, activitiesStr);
            new HomeScreen(m).setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FeelingsScreen.class.getName()).log(Level.SEVERE, null, ex);
            JFrame x = new JFrame();
            JOptionPane.showMessageDialog(x, "There was an error");
        }


    }//GEN-LAST:event_submitBttn7ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea activityTxtarea;
    private javax.swing.JTextArea activityTxtarea1;
    private javax.swing.JTextArea activityTxtarea2;
    private javax.swing.JTextArea activityTxtarea3;
    private javax.swing.JTextArea activityTxtarea4;
    private javax.swing.JComboBox<String> eatingHabits;
    private javax.swing.JComboBox<String> eatingHabits1;
    private javax.swing.JComboBox<String> eatingHabits2;
    private javax.swing.JComboBox<String> eatingHabits3;
    private javax.swing.JComboBox<String> eatingHabits4;
    private javax.swing.JComboBox<String> exerciseHabits;
    private javax.swing.JComboBox<String> exerciseHabits1;
    private javax.swing.JComboBox<String> exerciseHabits2;
    private javax.swing.JComboBox<String> exerciseHabits3;
    private javax.swing.JComboBox<String> exerciseHabits4;
    private javax.swing.JLabel goodLbl;
    private javax.swing.JLabel goodTxt;
    private javax.swing.JLabel happyLbl;
    private javax.swing.JSlider happyScale;
    private javax.swing.JSlider happyScale1;
    private javax.swing.JSlider happyScale2;
    private javax.swing.JSlider happyScale3;
    private javax.swing.JSlider happyScale4;
    private javax.swing.JLabel happyTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp5;
    private javax.swing.JPanel jpMain;
    private javax.swing.JLabel normalLbl;
    private javax.swing.JLabel normalTxt;
    private javax.swing.JLabel sadLbl;
    private javax.swing.JLabel sadTxt;
    private javax.swing.JSlider sleepScale;
    private javax.swing.JSlider sleepScale1;
    private javax.swing.JSlider sleepScale2;
    private javax.swing.JSlider sleepScale3;
    private javax.swing.JSlider sleepScale4;
    private javax.swing.JButton submitBttn3;
    private javax.swing.JButton submitBttn4;
    private javax.swing.JButton submitBttn5;
    private javax.swing.JButton submitBttn6;
    private javax.swing.JButton submitBttn7;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JLabel unhappyLbl;
    private javax.swing.JLabel unhappyTxt;
    // End of variables declaration//GEN-END:variables
}
