/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BACKEND.UserManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kyrab
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     *
     */
    private UserManager m;

    public HomeScreen(UserManager inManager) {
        initComponents();

        m = inManager;
        int rand = (int) ((Math.random() * 6 ) + 0);
       
        switch (rand) {
            case 1:
                dailyQuoteLbl.setText("'Your only limit is your mind'");
                break;
            case 2:
                dailyQuoteLbl.setText("“Don’t let yesterday take up too much of today.”");
                break;
            case 3:
                dailyQuoteLbl.setText("“Start by making one better food choice every day”");
                break;
            case 4:
                dailyQuoteLbl.setText("'No feeling is final'");
                break;
            case 5:
                dailyQuoteLbl.setText("'find hppiness in what you have'");
                break;
            case 6:
                dailyQuoteLbl.setText("'Goal setting is the secret to a compelling future'");
                break;

        }
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DiaryLibraryBttn = new javax.swing.JButton();
        homeUserLbl = new javax.swing.JLabel();
        FeelingScreenBttn = new javax.swing.JButton();
        StatScreenBttn = new javax.swing.JButton();
        dailyQuoteLbl = new javax.swing.JLabel();
        DiaryEntryBttn = new javax.swing.JButton();
        LearnScreenBttn = new javax.swing.JButton();
        treeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DiaryLibraryBttn.setBackground(new java.awt.Color(0, 102, 51));
        DiaryLibraryBttn.setText("Diary Library");
        DiaryLibraryBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaryLibraryBttnActionPerformed(evt);
            }
        });
        jPanel1.add(DiaryLibraryBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 415, 160, 30));

        homeUserLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeUser.png"))); // NOI18N
        homeUserLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeUserLblMouseClicked(evt);
            }
        });
        jPanel1.add(homeUserLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 100));

        FeelingScreenBttn.setBackground(new java.awt.Color(0, 102, 51));
        FeelingScreenBttn.setText("How do you feel ?");
        FeelingScreenBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeelingScreenBttnActionPerformed(evt);
            }
        });
        jPanel1.add(FeelingScreenBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 160, 30));

        StatScreenBttn.setBackground(new java.awt.Color(0, 102, 51));
        StatScreenBttn.setText("Mood Patterns");
        StatScreenBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatScreenBttnActionPerformed(evt);
            }
        });
        jPanel1.add(StatScreenBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 160, 30));

        dailyQuoteLbl.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        dailyQuoteLbl.setForeground(new java.awt.Color(0, 51, 0));
        dailyQuoteLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(dailyQuoteLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 490, 100));

        DiaryEntryBttn.setBackground(new java.awt.Color(0, 102, 51));
        DiaryEntryBttn.setText("Diary Entry");
        DiaryEntryBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaryEntryBttnActionPerformed(evt);
            }
        });
        jPanel1.add(DiaryEntryBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 160, 30));

        LearnScreenBttn.setBackground(new java.awt.Color(0, 102, 51));
        LearnScreenBttn.setText("Learn Something New");
        LearnScreenBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LearnScreenBttnActionPerformed(evt);
            }
        });
        jPanel1.add(LearnScreenBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 160, 30));

        treeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forest.png"))); // NOI18N
        jPanel1.add(treeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StatScreenBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatScreenBttnActionPerformed
        // TODO add your handling code here:
        dispose();
        new StatScreen(m).setVisible(true);
    }//GEN-LAST:event_StatScreenBttnActionPerformed

    private void DiaryEntryBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaryEntryBttnActionPerformed
        // TODO add your handling code here:
        dispose();
        new CalanderScreen(m).setVisible(true);
    }//GEN-LAST:event_DiaryEntryBttnActionPerformed

    private void LearnScreenBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LearnScreenBttnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LearnScreen(m).setVisible(true);
    }//GEN-LAST:event_LearnScreenBttnActionPerformed

    private void FeelingScreenBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeelingScreenBttnActionPerformed
        // TODO add your handling code here:
        dispose();
        new FeelingsScreen(m).setVisible(true);


    }//GEN-LAST:event_FeelingScreenBttnActionPerformed

    private void homeUserLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeUserLblMouseClicked
        JFrame k = new JFrame();
        JOptionPane.showMessageDialog(k, "Username:" + m.getUsername() + "\n" + "Name:" + m.getName());

    }//GEN-LAST:event_homeUserLblMouseClicked

    private void DiaryLibraryBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaryLibraryBttnActionPerformed
        dispose();
        try {
            new DiaryLibrary(m).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DiaryLibraryBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DiaryEntryBttn;
    private javax.swing.JButton DiaryLibraryBttn;
    private javax.swing.JButton FeelingScreenBttn;
    private javax.swing.JButton LearnScreenBttn;
    private javax.swing.JButton StatScreenBttn;
    private javax.swing.JLabel dailyQuoteLbl;
    private javax.swing.JLabel homeUserLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel treeLbl;
    // End of variables declaration//GEN-END:variables
}
